;;; package  --- coffee-config.el
;;; -*- coding: utf-8 -*-
;;;
;;; Commentary:
;;;
;;; Filename   : coffee-config.el
;;; Description: Emacs configuration for CoffeeScript development support
;;;
;;; elisp code for customizing the CoffeeScript development settings
;;;===========================================================================
(require 'coffee-mode)
;;;
;;; Code:
;;;
(eval-after-load 'coffee-mode
  '(progn
     ;; use 2 spaces for CoffeeScript
     (setq coffee-tab-width 2)

     ;; get rid of "Generated by CoffeeScript" header
     (add-to-list 'coffee-args-compile "--no-header")

     (defun aq-coffee-mode-defaults ()
       ;; Update the already compiled js on save
       (and (buffer-file-name)
            (file-exists-p (buffer-file-name))
            (file-exists-p (coffee-compiled-file-name (buffer-file-name)))
            (coffee-cos-mode t))
       ;; remap word based commands
       (subword-mode +1))

     (setq aq-coffee-mode-hook 'aq-coffee-mode-defaults)

     (add-hook 'coffee-mode-hook (lambda ()
                                   (run-hooks 'aq-coffee-mode-hook)))))

(provide 'coffee-config)

;; Local Variables:
;; coding: utf-8
;; mode: emacs-lisp
;; byte-compile-warnings: (not cl-functions)
;; End:

;;; coffee-config.el ends here
