(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(aquamacs-additional-fontsets
   (quote
    (("apple" "monaco*" "medium" "r" "normal" 9 "monaco")
     ("apple" "monaco*" "medium" "r" "normal" 10 "monaco")
     ("apple" "monaco*" "medium" "r" "normal" 11 "monaco")
     ("apple" "monaco*" "medium" "r" "normal" 12 "monaco")
     ("apple" "monaco*" "medium" "r" "normal" 13 "monaco")
     ("apple" "monaco*" "medium" "r" "normal" 14 "monaco")
     ("apple" "monaco*" "medium" "r" "normal" 16 "monaco")
     ("apple" "monaco*" "medium" "r" "normal" 18 "monaco")
     ("apple" "lucida grande*" "medium" "r" "normal" 9 "lucida")
     ("apple" "lucida grande*" "medium" "r" "normal" 10 "lucida")
     ("apple" "lucida grande*" "medium" "r" "normal" 11 "lucida")
     ("apple" "lucida grande*" "medium" "r" "normal" 12 "lucida")
     ("apple" "lucida grande*" "medium" "r" "normal" 13 "lucida")
     ("apple" "lucida grande*" "medium" "r" "normal" 14 "lucida")
     ("apple" "lucida grande*" "medium" "r" "normal" 16 "lucida")
     ("apple" "lucida grande*" "medium" "r" "normal" 18 "lucida")
     ("apple" "lucida sans typewrite*" "medium" "r" "normal" 9 "lucida_typewriter")
     ("apple" "lucida sans typewrite*" "medium" "r" "normal" 10 "lucida_typewriter")
     ("apple" "lucida sans typewrite*" "medium" "r" "normal" 12 "lucida_typewriter")
     ("apple" "lucida sans typewrite*" "medium" "r" "normal" 14 "lucida_typewriter")
     ("apple" "lucida console*" "medium" "r" nil 11 "lucida_console")
     (nil "courier*" "medium" "r" nil 11 "courier")
     (nil "courier*" "medium" "r" nil 13 "courier")
     (nil "bitstream vera sans mono" "medium" "r" "normal" 10 "vera_mono")
     (nil "bitstream vera sans mono" "medium" "r" "normal" 12 "vera_mono")
     (nil "bitstream vera sans mono" "medium" "r" "normal" 14 "vera_mono"))) t)
 '(aquamacs-customization-version-id 308 t)
 '(aquamacs-tool-bar-user-customization nil t)
 '(company-ghc-show-info t)
 '(custom-safe-themes
   (quote
    ("3cd28471e80be3bd2657ca3f03fbb2884ab669662271794360866ab60b6cb6e6" "251348dcb797a6ea63bbfe3be4951728e085ac08eee83def071e4d2e3211acc3" default)))
 '(default-frame-alist
    (quote
     ((tool-bar-lines . 1)
      (menu-bar-lines . 1)
      (foreground-color . "Black")
      (background-color . "White")
      (cursor-type . box)
      (cursor-color . "Red")
      (vertical-scroll-bars . right)
      (internal-border-width . 0)
      (fringe)
      (left-fringe . 4)
      (right-fringe . 0))))
 '(git-gutter:added-sign "☀")
 '(git-gutter:deleted-sign "☂")
 '(git-gutter:modified-sign "☁")
 '(git-gutter:window-width 2)
 '(haskell-font-lock-symbols t)
 '(haskell-process-auto-import-loaded-modules t)
 '(haskell-process-log t)
 '(haskell-process-show-debug-tips t)
 '(haskell-process-suggest-haskell-docs-imports t)
 '(haskell-process-suggest-hoogle-imports t)
 '(haskell-process-suggest-remove-import-lines t)
 '(haskell-process-type (quote ghci))
 '(haskell-process-use-presentation-mode t)
 '(haskell-stylish-on-save t)
 '(haskell-tags-on-save nil)
 '(hindent-style "chris-done")
 '(inferior-haskell-find-haddock nil)
 '(ns-tool-bar-display-mode (quote both) t)
 '(ns-tool-bar-size-mode (quote regular) t)
 '(one-buffer-one-frame-mode t nil (aquamacs-frame-setup))
 '(shm-auto-insert-bangs t)
 '(shm-auto-insert-skeletons t)
 '(shm-use-hdevtools t)
 '(shm-use-presentation-mode t)
 '(visual-line-mode nil t))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(neo-banner-face ((t :inherit shadow)))
 '(neo-button-face ((t :inherit dired-directory)))
 '(neo-dir-link-face ((t :inherit dired-directory)))
 '(neo-expand-btn-face ((t :inherit button)))
 '(neo-file-link-face ((t :inherit default)))
 '(neo-header-face ((t :inherit shadow)))
 '(neo-root-dir-face ((t :inherit link-visited :underline nil))))
