;; -*- mode: emacs-lisp; coding: utf-8-unix -*-
;; Minibuffer history file, automatically generated by ‘savehist’.

(setq savehist-minibuffer-history-variables '(elpy-doc-history minibuffer-history helm-M-x-input-history))
(setq elpy-doc-history '("detector"))
(setq minibuffer-history '("/tmp/facial_landmarks.py" "c"))
(setq helm-M-x-input-history '("electr" "change"))
(setq search-ring 'nil)
(setq regexp-search-ring 'nil)
(setq kill-ring 'nil)
