#!/usr/bin/env escript

-export([main/1]).
main([File_Name]) ->
    Includes = case filelib:is_dir("../deps") of
                   false ->
                       [{i, "../include"}];
                   true ->
                       {ok, Deps} = file:list_dir("../deps"),
                       [{i, "../include"}| [{i,Di} || D <- Deps,
                              begin
                                  Di = "../deps/" ++ D ++ "/include",
                                  filelib:is_dir(Di)
                              end]]
               end,
    IncludesAllApps = [{i, "../include"}, {i, "../.."}, {i, "../../../deps"} | Includes],
    compile:file(File_Name, [warn_obsolete_guard,
                             warn_unused_import,
                             warn_shadow_vars,
                             warn_export_vars,
                             strong_validation,
                             report | IncludesAllApps]).
